import type { ZeroMode } from "./zeros";

export type Msg = { role: "user" | "assistant"; content: string };

export async function streamChat(
  messages: Msg[],
  mode: ZeroMode,
  memories: string[],
  onDelta: (full: string) => void,
  signal?: AbortSignal,
): Promise<string> {
  // Safety net for the home-screen image suggestion. The suggestion can race
  // React's mode state update, so use a same-origin image endpoint here instead
  // of putting a giant data/blob URL through react-markdown.
  if (mode === "chat") {
    const lastUser = [...messages].reverse().find((m) => m.role === "user")?.content?.trim() ?? "";
    if (/^render a 3d glass orb$/i.test(lastUser)) {
      const imageUrl = `/api/generate-image?prompt=${encodeURIComponent(lastUser)}`;
      const downloadUrl = `/api/generate-image?prompt=${encodeURIComponent(lastUser)}&download=1`;
      const full = `I’m conjuring a luminous **3D glass orb** now — crystal physics, studio lighting, zero existential paperwork. 🔮✨\n\n![Generated by Zeros](${imageUrl})\n\n[Download the PNG](${downloadUrl})`;
      onDelta(full);
      return full;
    }
  }

  const res = await fetch("/api/chat", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ messages, mode, memories }),
    signal: signal ?? null,
  });
  if (!res.ok || !res.body) {
    throw new Error((await res.text().catch(() => "")) || `Error ${res.status}`);
  }

  const reader = res.body.getReader();
  const decoder = new TextDecoder();
  let buffer = "";
  let full = "";
  for (;;) {
    const { done, value } = await reader.read();
    if (done) break;
    buffer += decoder.decode(value, { stream: true });
    const parts = buffer.split("\n");
    buffer = parts.pop() ?? "";
    for (const line of parts) {
      const t = line.trim();
      if (!t.startsWith("data:")) continue;
      const payload = t.slice(5).trim();
      if (!payload || payload === "[DONE]") continue;
      try {
        const json = JSON.parse(payload);
        const delta = json?.choices?.[0]?.delta?.content;
        if (typeof delta === "string" && delta) {
          full += delta;
          onDelta(full);
        }
      } catch {}
    }
  }
  buffer += decoder.decode();
  const trailing = buffer.trim();
  if (trailing.startsWith("data:")) {
    const payload = trailing.slice(5).trim();
    if (payload && payload !== "[DONE]") {
      try {
        const json = JSON.parse(payload);
        const delta = json?.choices?.[0]?.delta?.content;
        if (typeof delta === "string" && delta) {
          full += delta;
          onDelta(full);
        }
      } catch {}
    }
  }
  if (!full.trim()) throw new Error("Zeros received an empty generation. Please try again.");
  return full;
}

function blobToPng(blob: Blob): Promise<Blob> {
  if (blob.type === "image/png") return Promise.resolve(blob);
  return createImageBitmap(blob).then((bitmap) => {
    try {
      const canvas = document.createElement("canvas");
      canvas.width = bitmap.width;
      canvas.height = bitmap.height;
      const context = canvas.getContext("2d");
      if (!context) throw new Error("PNG conversion is unavailable in this browser");
      context.drawImage(bitmap, 0, 0);
      return new Promise<Blob>((resolve, reject) => {
        canvas.toBlob((png) => (png ? resolve(png) : reject(new Error("PNG encoding failed"))), "image/png");
      });
    } finally {
      bitmap.close();
    }
  });
}

export async function downloadImageAsPng(src: string, filename = "zeros-image.png"): Promise<void> {
  const response = await fetch(src, { credentials: "same-origin" });
  if (!response.ok) throw new Error(`Image download returned HTTP ${response.status}`);
  const blob = await response.blob();
  const png = await blobToPng(blob);
  const objectUrl = URL.createObjectURL(png);
  try {
    const anchor = document.createElement("a");
    anchor.href = objectUrl;
    anchor.download = filename;
    anchor.rel = "noopener";
    document.body.appendChild(anchor);
    anchor.click();
    anchor.remove();
  } finally {
    window.setTimeout(() => URL.revokeObjectURL(objectUrl), 10_000);
  }
}

export async function generateImage(prompt: string): Promise<string> {
  const res = await fetch("/api/generate-image", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ prompt, stream: false }),
  });
  if (!res.ok) {
    const text = await res.text().catch(() => "");
    let message = text || `Error ${res.status}`;
    try {
      const json = JSON.parse(text) as { error?: string };
      message = json.error || message;
    } catch {}
    throw new Error(message);
  }

  const blob = await res.blob();
  if (!blob.type.startsWith("image/")) throw new Error("Pollinations returned a non-image response.");
  return URL.createObjectURL(blob);
}

/** Tripo AI text-to-3D: creates a job, polls it, resolves with a .glb URL. */
export async function generateModel(
  prompt: string,
  onProgress?: (pct: number) => void,
): Promise<string> {
  const create = await fetch("/api/model", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ prompt }),
  });
  const created = (await create.json().catch(() => ({}))) as {
    taskId?: string;
    error?: string;
  };
  if (!create.ok || !created.taskId) {
    throw new Error(created.error || "Tripo could not start the 3D job.");
  }

  const started = Date.now();
  for (;;) {
    await new Promise((r) => setTimeout(r, 3000));
    const res = await fetch(`/api/model?id=${encodeURIComponent(created.taskId)}`);
    const json = (await res.json().catch(() => ({}))) as {
      status?: string;
      progress?: number;
      url?: string | null;
      error?: string;
    };
    if (!res.ok || json.error) throw new Error(json.error || "Tripo status check failed.");
    onProgress?.(json.progress ?? 0);
    if (json.status === "success" && json.url) return json.url;
    if (["failed", "cancelled", "banned", "expired", "unknown"].includes(json.status ?? ""))
      throw new Error(`Tripo job ${json.status}.`);
    if (Date.now() - started > 8 * 60 * 1000) throw new Error("Tripo job timed out.");
  }
}
