import type { ZeroMode } from "./zeros";

export type Msg = { role: "user" | "assistant"; content: string };

export async function streamChat(
  messages: Msg[],
  mode: ZeroMode,
  memories: string[],
  onDelta: (full: string) => void,
  signal?: AbortSignal,
): Promise<string> {
  // Safety net for the home-screen image suggestion. React can commit the mode
  // change after the click handler calls send(), so keep this exact image intent
  // from silently falling through to text chat.
  if (mode === "chat") {
    const lastUser = [...messages].reverse().find((m) => m.role === "user")?.content?.trim() ?? "";
    if (/^render a 3d glass orb$/i.test(lastUser)) {
      const src = await generateImage(lastUser);
      const pngSrc = await imageUrlToPngDataUrl(src);
      const downloadable = toDownloadDataUrl(pngSrc);
      const full = `I’m conjuring a luminous **3D glass orb** now — crystal physics, studio lighting, zero existential paperwork. 🔮✨\n\n![Generated by Zeros](${pngSrc})\n\n[Download the PNG](${downloadable})`;
      onDelta(full);
      return full;
    }
  }

  const res = await fetch("/api/chat", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ messages, mode, memories }),
    signal: signal ?? null,
  });
  if (!res.ok || !res.body) {
    throw new Error((await res.text().catch(() => "")) || `Error ${res.status}`);
  }

  const reader = res.body.getReader();
  const decoder = new TextDecoder();
  let buffer = "";
  let full = "";
  for (;;) {
    const { done, value } = await reader.read();
    if (done) break;
    buffer += decoder.decode(value, { stream: true });
    const parts = buffer.split("\n");
    buffer = parts.pop() ?? "";
    for (const line of parts) {
      const t = line.trim();
      if (!t.startsWith("data:")) continue;
      const payload = t.slice(5).trim();
      if (!payload || payload === "[DONE]") continue;
      try {
        const json = JSON.parse(payload);
        const delta = json?.choices?.[0]?.delta?.content;
        if (typeof delta === "string" && delta) {
          full += delta;
          onDelta(full);
        }
      } catch {}
    }
  }
  buffer += decoder.decode();
  const trailing = buffer.trim();
  if (trailing.startsWith("data:")) {
    const payload = trailing.slice(5).trim();
    if (payload && payload !== "[DONE]") {
      try {
        const json = JSON.parse(payload);
        const delta = json?.choices?.[0]?.delta?.content;
        if (typeof delta === "string" && delta) {
          full += delta;
          onDelta(full);
        }
      } catch {}
    }
  }
  if (!full.trim()) throw new Error("Zeros received an empty generation. Please try again.");
  return full;
}

function findB64(obj: unknown): string | null {
  if (!obj || typeof obj !== "object") return null;
  for (const [k, v] of Object.entries(obj as Record<string, unknown>)) {
    if (typeof v === "string") {
      if (k === "b64_json" && v.length > 100) return `data:image/png;base64,${v}`;
      if (v.startsWith("data:image/")) return v;
    } else if (v && typeof v === "object") {
      const found = findB64(v);
      if (found) return found;
    }
  }
  return null;
}

function imageUrlToPngDataUrl(url: string): Promise<string> {
  if (url.startsWith("data:image/png")) return Promise.resolve(url);

  return fetch(url, { mode: "cors", credentials: "omit" })
    .then(async (response) => {
      if (!response.ok) throw new Error(`image download returned HTTP ${response.status}`);
      const blob = await response.blob();
      if (!blob.type.startsWith("image/")) throw new Error("Pollinations returned a non-image response");
      return createImageBitmap(blob).then((bitmap) => {
        try {
          const canvas = document.createElement("canvas");
          canvas.width = bitmap.width;
          canvas.height = bitmap.height;
          const context = canvas.getContext("2d");
          if (!context) throw new Error("PNG conversion is unavailable in this browser");
          context.drawImage(bitmap, 0, 0);
          return canvas.toDataURL("image/png");
        } finally {
          bitmap.close();
        }
      });
    });
}

function toDownloadDataUrl(src: string): string {
  if (!src.startsWith("data:")) return src;
  const comma = src.indexOf(",");
  if (comma < 0) return src;
  const meta = src.slice(0, comma);
  const data = src.slice(comma + 1);
  if (!/;base64/i.test(meta)) return src;
  return `data:application/octet-stream;base64,${data}`;
}

export async function downloadImageAsPng(src: string, filename = "zeros-image.png"): Promise<void> {
  try {
    const pngSrc = await imageUrlToPngDataUrl(src);
    const response = await fetch(pngSrc);
    const blob = await response.blob();
    const objectUrl = URL.createObjectURL(blob);
    try {
      const anchor = document.createElement("a");
      anchor.href = objectUrl;
      anchor.download = filename;
      anchor.rel = "noopener";
      document.body.appendChild(anchor);
      anchor.click();
      anchor.remove();
    } finally {
      window.setTimeout(() => URL.revokeObjectURL(objectUrl), 10_000);
    }
  } catch (error) {
    // Never navigate to an external Pollinations URL. That is what caused the
    // mobile browser to leave/reload Zeros. Use a local blob download instead.
    throw error instanceof Error ? error : new Error("PNG download failed.");
  }
}

export async function generateImage(prompt: string): Promise<string> {
  const res = await fetch("/api/generate-image", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ prompt, stream: false }),
  });
  const json = (await res.json().catch(() => ({}))) as {
    image?: string;
    error?: string;
  };
  if (!res.ok) throw new Error(json.error || `Error ${res.status}`);

  const img = findB64(json);
  if (img) return img;
  if (typeof json.image === "string" && json.image.startsWith("data:image/")) return json.image;

  throw new Error("Pollinations returned no usable image data. Please try again.");
}

/** Tripo AI text-to-3D: creates a job, polls it, resolves with a .glb URL. */
export async function generateModel(
  prompt: string,
  onProgress?: (pct: number) => void,
): Promise<string> {
  const create = await fetch("/api/model", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ prompt }),
  });
  const created = (await create.json().catch(() => ({}))) as {
    taskId?: string;
    error?: string;
  };
  if (!create.ok || !created.taskId) {
    throw new Error(created.error || "Tripo could not start the 3D job.");
  }

  const started = Date.now();
  for (;;) {
    await new Promise((r) => setTimeout(r, 3000));
    const res = await fetch(`/api/model?id=${encodeURIComponent(created.taskId)}`);
    const json = (await res.json().catch(() => ({}))) as {
      status?: string;
      progress?: number;
      url?: string | null;
      error?: string;
    };
    if (!res.ok || json.error) throw new Error(json.error || "Tripo status check failed.");
    onProgress?.(json.progress ?? 0);
    if (json.status === "success" && json.url) return json.url;
    if (["failed", "cancelled", "banned", "expired", "unknown"].includes(json.status ?? ""))
      throw new Error(`Tripo job ${json.status}.`);
    if (Date.now() - started > 8 * 60 * 1000) throw new Error("Tripo job timed out.");
  }
}
