import type { ZeroMode } from "./zeros";

export type Msg = { role: "user" | "assistant"; content: string };

let imageDownloadInterceptorInstalled = false;

function installImageDownloadInterceptor(): void {
  if (imageDownloadInterceptorInstalled || typeof document === "undefined") return;
  imageDownloadInterceptorInstalled = true;

  document.addEventListener("click", (event) => {
    const target = event.target as HTMLElement | null;
    const anchor = target?.closest("a") as HTMLAnchorElement | null;
    if (!anchor || !/download\s+the\s+png/i.test(anchor.textContent ?? "")) return;

    let url: URL;
    try {
      url = new URL(anchor.href, window.location.href);
    } catch {
      return;
    }
    if (url.pathname !== "/api/generate-image" || url.searchParams.get("download") !== "1") return;

    event.preventDefault();
    event.stopPropagation();
    void downloadImageAsPng(url.toString(), "keris-image.png").catch(() => {});
  });
}

export async function streamChat(
  messages: Msg[],
  mode: ZeroMode,
  memories: string[],
  onDelta: (full: string) => void,
  signal?: AbortSignal,
  onFinishReason?: (reason: string | null) => void,
): Promise<string> {
  if (mode === "chat") {
    const lastUser = [...messages].reverse().find((m) => m.role === "user")?.content?.trim() ?? "";
    if (/^render a 3d glass orb$/i.test(lastUser)) {
      installImageDownloadInterceptor();
      const imageUrl = `/api/generate-image?prompt=${encodeURIComponent(lastUser)}`;
      const downloadUrl = `/api/generate-image?prompt=${encodeURIComponent(lastUser)}&download=1`;
      const full = `I'm conjuring a luminous **3D glass orb** now — crystal physics, studio lighting, zero existential paperwork. 🔮✨\n\n![Generated by Keris](${imageUrl})\n\n[Download the PNG](${downloadUrl})`;
      onDelta(full);
      return full;
    }
  }

  // Model sculpt needs headroom: structured JSON + stream fallback can take a minute.
  const timeoutMs = mode === "model" ? 180_000 : mode === "web" ? 150_000 : 120_000;
  const controller = signal ? null : new AbortController();
  const timeout = controller ? window.setTimeout(() => controller.abort(), timeoutMs) : null;
  const res = await fetch("/api/chat", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ messages, mode, memories }),
    signal: signal ?? controller?.signal ?? null,
  }).finally(() => {
    if (timeout !== null) window.clearTimeout(timeout);
  });
  if (!res.ok || !res.body) {
    throw new Error((await res.text().catch(() => "")) || `Error ${res.status}`);
  }

  const reader = res.body.getReader();
  const decoder = new TextDecoder();
  let buffer = "";
  let full = "";
  let finishReason: string | null = null;
  for (;;) {
    const { done, value } = await reader.read();
    if (done) break;
    buffer += decoder.decode(value, { stream: true });
    const parts = buffer.split("\n");
    buffer = parts.pop() ?? "";
    for (const line of parts) {
      const t = line.trim();
      if (!t.startsWith("data:")) continue;
      const payload = t.slice(5).trim();
      if (!payload || payload === "[DONE]") continue;
      try {
        const json = JSON.parse(payload);
        const choice = json?.choices?.[0];
        const reason = choice?.finish_reason;
        if (typeof reason === "string" && reason) finishReason = reason;
        const delta = choice?.delta?.content;
        if (typeof delta === "string" && delta) {
          full += delta;
          onDelta(full);
        }
      } catch {}
    }
  }
  buffer += decoder.decode();
  const trailing = buffer.trim();
  if (trailing.startsWith("data:")) {
    const payload = trailing.slice(5).trim();
    if (payload && payload !== "[DONE]") {
      try {
        const json = JSON.parse(payload);
        const choice = json?.choices?.[0];
        const reason = choice?.finish_reason;
        if (typeof reason === "string" && reason) finishReason = reason;
        const delta = choice?.delta?.content;
        if (typeof delta === "string" && delta) {
          full += delta;
          onDelta(full);
        }
      } catch {}
    }
  }
  if (!full.trim()) throw new Error("Keris received an empty generation. Please try again.");
  onFinishReason?.(finishReason);
  return full;
}

function blobToPng(blob: Blob): Promise<Blob> {
  if (blob.type === "image/png") return Promise.resolve(blob);
  return createImageBitmap(blob).then((bitmap) => {
    try {
      const canvas = document.createElement("canvas");
      canvas.width = bitmap.width;
      canvas.height = bitmap.height;
      const context = canvas.getContext("2d");
      if (!context) throw new Error("PNG conversion is unavailable in this browser");
      context.drawImage(bitmap, 0, 0);
      return new Promise<Blob>((resolve, reject) => {
        canvas.toBlob(
          (png) => (png ? resolve(png) : reject(new Error("PNG encoding failed"))),
          "image/png",
        );
      });
    } finally {
      bitmap.close();
    }
  });
}

export async function downloadImageAsPng(src: string, filename = "keris-image.png"): Promise<void> {
  const response = await fetch(src, { credentials: "same-origin" });
  if (!response.ok) throw new Error(`Image download returned HTTP ${response.status}`);
  const blob = await response.blob();
  const png = await blobToPng(blob);
  const objectUrl = URL.createObjectURL(png);
  try {
    const anchor = document.createElement("a");
    anchor.href = objectUrl;
    anchor.download = filename;
    anchor.rel = "noopener";
    document.body.appendChild(anchor);
    anchor.click();
    anchor.remove();
  } finally {
    window.setTimeout(() => URL.revokeObjectURL(objectUrl), 10_000);
  }
}

export async function generateImage(prompt: string): Promise<string> {
  const res = await fetch("/api/generate-image", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ prompt, stream: false }),
  });
  if (!res.ok) {
    const text = await res.text().catch(() => "");
    let message = text || `Error ${res.status}`;
    try {
      const json = JSON.parse(text) as { error?: string };
      message = json.error || message;
    } catch {}
    throw new Error(message);
  }

  const blob = await res.blob();
  if (!blob.type.startsWith("image/")) throw new Error("Pollinations returned a non-image response.");
  return URL.createObjectURL(blob);
}
