import { groqText, manusChat } from "@/lib/providers.server";

type V=[number,number,number];
type P={type:string;size?:V;radius?:number;height?:number;position?:V;rotation?:V;scale?:V;color?:string;metallic?:number;roughness?:number;segments?:number};
type B={parts:P[];background?:string};
type M={p:V[];n:V[];uv:number[];i:number[];color:[number,number,number,number];metallic:number;roughness:number};
const clamp=(n:number,a:number,b:number)=>Math.max(a,Math.min(b,n));
const add=(a:V,b:V):V=>[a[0]+b[0],a[1]+b[1],a[2]+b[2]];
const mul=(a:V,s:number):V=>[a[0]*s,a[1]*s,a[2]*s];
const unit=(a:V):V=>{const d=Math.hypot(...a)||1;return[a[0]/d,a[1]/d,a[2]/d]};
const rotate=(p:V,r:V):V=>{let[x,y,z]=p;const[cx,sx]=[Math.cos(r[0]),Math.sin(r[0])], [cy,sy]=[Math.cos(r[1]),Math.sin(r[1])],[cz,sz]=[Math.cos(r[2]),Math.sin(r[2])];[y,z]=[y*cx-z*sx,y*sx+z*cx];[x,z]=[x*cy+z*sy,-x*sy+z*cy];[x,y]=[x*cz-y*sz,x*sz+y*cz];return[x,y,z]};
function rgb(h:string|undefined):[number,number,number,number]{const s=(h||"#8aa0b8").replace("#","");const q=s.length===3?s.split("").map(x=>x+x).join(""):s;const n=parseInt(q,16)||0x8aa0b8;return[((n>>16)&255)/255,((n>>8)&255)/255,(n&255)/255,1]}
function box(s:V){const[x,y,z]=s.map(n=>Math.max(.02,n/2)) as V;const f:[V,V[]][]=[[[1,0,0],[[x,-y,-z],[x,y,-z],[x,y,z],[x,-y,z]]],[[-1,0,0],[[-x,-y,z],[-x,y,z],[-x,y,-z],[-x,-y,-z]]],[[0,1,0],[[-x,y,-z],[-x,y,z],[x,y,z],[x,y,-z]]],[[0,-1,0],[[-x,-y,z],[-x,-y,-z],[x,-y,-z],[x,-y,z]]],[[0,0,1],[[-x,-y,z],[x,-y,z],[x,y,z],[-x,y,z]]],[[0,0,-1],[[x,-y,-z],[-x,-y,-z],[-x,y,-z],[x,y,-z]]]];const p:V[]=[],n:V[]=[],uv:number[]=[],i:number[]=[];for(const[nn,ps]of f){const b=p.length;ps.forEach((q,k)=>{p.push(q);n.push(nn);uv.push(k===1||k===2?1:0,k>=2?1:0)});i.push(b,b+1,b+2,b,b+2,b+3)}return{p,n,uv,i}}
function sphere(r:number,s=28,rings=18){const p:V[]=[],n:V[]=[],uv:number[]=[],i:number[]=[];for(let y=0;y<=rings;y++){const t=y/rings,a=Math.PI*t;for(let x=0;x<=s;x++){const u=x/s*Math.PI*2,q:V=[Math.sin(a)*Math.cos(u),Math.cos(a),Math.sin(a)*Math.sin(u)];p.push(mul(q,r));n.push(q);uv.push(x/s,1-t)}}for(let y=0;y<rings;y++)for(let x=0;x<s;x++){const a=y*(s+1)+x,b=a+1,c=a+s+1,d=c+1;i.push(a,c,b,b,c,d)}return{p,n,uv,i}}
function cyl(r:number,h:number,s=28){const p:V[]=[],n:V[]=[],uv:number[]=[],i:number[]=[];for(let y=0;y<=1;y++)for(let x=0;x<=s;x++){const a=x/s*Math.PI*2,q:V=[Math.cos(a),0,Math.sin(a)];p.push([q[0]*r,y?h/2:-h/2,q[2]*r]);n.push(q);uv.push(x/s,y)}for(let x=0;x<s;x++){const a=x,b=a+1,c=a+s+1,d=c+1;i.push(a,c,b,b,c,d)}return{p,n,uv,i}}
function cone(r:number,h:number,s=28){const p:V[]=[],n:V[]=[],uv:number[]=[],i:number[]=[];for(let x=0;x<=s;x++){const a=x/s*Math.PI*2,q:V=[Math.cos(a),0,Math.sin(a)];p.push([q[0]*r,-h/2,q[2]*r]);n.push(unit([q[0],r/h,q[2]]));uv.push(x/s,0)}p.push([0,h/2,0]);n.push([0,1,0]);uv.push(.5,1);const tip=p.length-1;for(let x=0;x<s;x++)i.push(x,tip,x+1);return{p,n,uv,i}}
function torus(R:number,r:number,s=32,t=10){const p:V[]=[],n:V[]=[],uv:number[]=[],i:number[]=[];for(let x=0;x<=s;x++)for(let y=0;y<=t;y++){const a=x/s*Math.PI*2,q=y/t*Math.PI*2,qv:V=[Math.cos(a)*Math.cos(q),Math.sin(q),Math.sin(a)*Math.cos(q)];p.push([(R+r*Math.cos(q))*Math.cos(a),r*Math.sin(q),(R+r*Math.cos(q))*Math.sin(a)]);n.push(qv);uv.push(x/s,y/t)}for(let x=0;x<s;x++)for(let y=0;y<t;y++){const a=x*(t+1)+y,b=a+1,c=a+t+1,d=c+1;i.push(a,c,b,b,c,d)}return{p,n,uv,i}}
function primitive(x:P){const t=x.type.toLowerCase(),r=Math.max(.03,x.radius??.5),h=Math.max(.03,x.height??1),s=clamp(Math.round(x.segments??28),8,48);if(["box","cube","panel","armor"].includes(t))return box(x.size??[1,1,1]);if(["cylinder","rod","limb"].includes(t))return cyl(r,h,s);if(["cone","spike"].includes(t))return cone(r,h,s);if(["torus","ring","loop"].includes(t))return torus(x.radius?x.radius*2:r*2,x.radius??r*.3,s,10);if(["capsule","rounded"].includes(t)){const a=cyl(r,h,s),b=sphere(r,s,Math.floor(s*.65)),c=sphere(r,s,Math.floor(s*.65));for(const q of b.p)q[1]+=h/2;for(const q of c.p)q[1]-=h/2;return{p:[...a.p,...b.p,...c.p],n:[...a.n,...b.n,...c.n],uv:[...a.uv,...b.uv,...c.uv],i:[...a.i,...b.i.map(q=>q+a.p.length),...c.i.map(q=>q+a.p.length+b.p.length)]}}return sphere(r,s,Math.floor(s*.65))}
function scene(bp:B):M[]{return bp.parts.slice(0,64).map(x=>{const q=primitive(x),r=x.rotation??[0,0,0],pos=x.position??[0,0,0],sc=x.scale??[1,1,1];return{p:q.p.map(z=>add(rotate([z[0]*sc[0],z[1]*sc[1],z[2]*sc[2]],r),pos)),n:q.n.map(z=>unit(rotate(z,r))),uv:q.uv,i:q.i,color:rgb(x.color),metallic:clamp(x.metallic??.25,0,1),roughness:clamp(x.roughness??.35,.05,1)}})}
function b64(a:Uint8Array){let s="";for(let k=0;k<a.length;k+=0x8000)s+=String.fromCharCode(...a.subarray(k,Math.min(k+0x8000,a.length)));return btoa(s)}
function bytes(a:ArrayBuffer|ArrayBufferView){return new Uint8Array(a instanceof ArrayBuffer?a:a.buffer,a instanceof ArrayBuffer?0:a.byteOffset,a instanceof ArrayBuffer?a.byteLength:a.byteLength)}
function gltf(ms:M[]):string{const buffers:string[]=[];const meshes:any[]=[];const mats:any[]=[];const nodes:any[]=[];for(let z=0;z<ms.length;z++){const m=ms[z],pos=new Float32Array(m.p.flat()),nor=new Float32Array(m.n.flat()),uv=new Float32Array(m.uv),idx=new Uint32Array(m.i);const bin=new Uint8Array(pos.byteLength+nor.byteLength+uv.byteLength+idx.byteLength);let o=0;bin.set(bytes(pos),o);const po=o;o+=pos.byteLength;bin.set(bytes(nor),o);const no=o;o+=nor.byteLength;bin.set(bytes(uv),o);const uo=o;o+=uv.byteLength;bin.set(bytes(idx),o);const io=o;buffers.push(`data:application/octet-stream;base64,${b64(bin)}`);const bv=[{buffer:z,byteOffset:po,byteLength:pos.byteLength,target:34962},{buffer:z,byteOffset:no,byteLength:nor.byteLength,target:34962},{buffer:z,byteOffset:uo,byteLength:uv.byteLength,target:34962},{buffer:z,byteOffset:io,byteLength:idx.byteLength,target:34963}];const ac=[{bufferView:0,componentType:5126,count:m.p.length,type:"VEC3"},{bufferView:1,componentType:5126,count:m.n.length,type:"VEC3"},{bufferView:2,componentType:5126,count:m.p.length,type:"VEC2"},{bufferView:3,componentType:5125,count:m.i.length,type:"SCALAR"}];const mi=mats.length;mats.push({pbrMetallicRoughness:{baseColorFactor:m.color,metallicFactor:m.metallic,roughnessFactor:m.roughness}});meshes.push({primitives:[{attributes:{POSITION:0,NORMAL:1,TEXCOORD_0:2},indices:3,material:mi}],bufferViews:bv,accessors:ac});nodes.push({mesh:z,name:`ZerosPart${z}`})}const allViews:any[]=[],allAcc:any[]=[];meshes.forEach((m,z)=>{const baseV=allViews.length,baseA=allAcc.length;allViews.push(...m.bufferViews.map((v:any)=>({...v,buffer:z})));allAcc.push(...m.accessors.map((a:any)=>({...a,bufferView:a.bufferView+baseV})));m.primitives[0].attributes={POSITION:baseA,NORMAL:baseA+1,TEXCOORD_0:baseA+2};m.primitives[0].indices=baseA+3;delete m.bufferViews;delete m.accessors});const doc={asset:{version:"2.0",generator:"Zeros Native 3D"},scene:0,scenes:[{nodes:nodes.map((_,i)=>i)}],nodes,meshes,materials:mats,bufferViews:allViews,accessors:allAcc,buffers:buffers.map(uri=>({uri,byteLength:0}))};return`data:model/gltf+json;base64,${b64(new TextEncoder().encode(JSON.stringify(doc)))}`}
function preview(ms:M[],bg:string){const polys:string[]=[];const project=(q:V)=>[320+(q[0]-q[2])*45,300-q[1]*45-(q[0]+q[2])*14] as V;for(const m of ms)for(let k=0;k<m.i.length;k+=3){const a=m.p[m.i[k]],b=m.p[m.i[k+1]],c=m.p[m.i[k+2]];if(!a||!b||!c)continue;const A=project(a),B=project(b),C=project(c);const light=clamp(.55+(m.n[m.i[k]][1]+m.n[m.i[k+1]][1]+m.n[m.i[k+2]][1])/6,.2,1);const col=`rgb(${Math.round(m.color[0]*255*light)},${Math.round(m.color[1]*255*light)},${Math.round(m.color[2]*255*light)})`;polys.push(`<polygon points="${A[0]},${A[1]} ${B[0]},${B[1]} ${C[0]},${C[1]}" fill="${col}"/>`)}const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="640" height="640"><rect width="640" height="640" fill="${bg}"/><g stroke="#ffffff18" stroke-width=".5">${polys.join("")}</g><text x="24" y="615" fill="white" font-family="sans-serif" font-size="16">ZEROS NATIVE 3D • strict inspection render</text></svg>`;return`data:image/svg+xml;base64,${b64(new TextEncoder().encode(svg))}`}
function json(text:string){const c=text.replace(/^```(?:json)?\s*/i,"").replace(/```\s*$/i,"").trim();try{return JSON.parse(c)}catch{const m=c.match(/\{[\s\S]*\}/);if(!m)return null;try{return JSON.parse(m[0])}catch{return null}}}
async function blueprint(prompt:string):Promise<B>{const sys=`Design a detailed procedural 3D blueprint for Zeros Native 3D. Zeros builds every polygon itself. Never mention external 3D generators. Return ONLY JSON: {"background":"#hex","parts":[{"type":"sphere|box|cylinder|cone|torus|capsule|panel|limb|spike","size":[x,y,z],"radius":number,"height":number,"position":[x,y,z],"rotation":[rx,ry,rz],"scale":[x,y,z],"color":"#hex","metallic":0-1,"roughness":0.05-1,"segments":8-48}]}. Use up to 48 parts, coordinate Y up, dimensions -6..6, and include every important requested component with deliberate proportions and symmetry.`;const a=await manusChat(sys,[{role:"user",content:prompt}],45000);const b=a?json(a):null;if(b?.parts?.length)return b as B;const g=await groqText(sys,prompt);const c=g?json(g):null;if(c?.parts?.length)return c as B;return{background:"#0b1020",parts:[{type:"capsule",radius:1,height:2.6,position:[0,1.3,0],color:"#8aa0b8"},{type:"sphere",radius:1,position:[0,3,0],color:"#aabbd0"},{type:"cylinder",radius:.3,height:2.5,position:[-1.2,1.4,0],color:"#596b80"},{type:"cylinder",radius:.3,height:2.5,position:[1.2,1.4,0],color:"#596b80"}]}}
export async function generateNativeModel(prompt:string){const bp=await blueprint(prompt);const ms=scene(bp);if(!ms.length)throw new Error("Zeros Native 3D produced an empty scene.");return{url:gltf(ms),previewUrl:preview(ms,bp.background||"#0b1020")}}
