import { GEMINI_TEXT_FALLBACKS, GEMINI_TEXT_MODEL, geminiKeys } from "@/lib/providers.server";

export type StudioReview = { score:number; passed:boolean; issues:string[]; improvedPrompt:string };
type GeminiPart={text?:string};
const visionModels=[GEMINI_TEXT_MODEL,...GEMINI_TEXT_FALLBACKS];
function clampPrompt(prompt:string,max=1024){return prompt.replace(/\s+/g," ").trim().slice(0,max);}
function parseDataUrl(source:string){const m=source.match(/^data:(image\/[a-zA-Z0-9.+-]+);base64,(.+)$/s);return m?.[1]&&m[2]?{mimeType:m[1],data:m[2]}:null;}
function bytesToBase64(bytes:Uint8Array){let binary="";for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,Math.min(i+0x8000,bytes.length)));return btoa(binary);}
async function imageToInlineData(source:string){const direct=parseDataUrl(source);if(direct)return direct;if(!/^https?:\/\//i.test(source))return null;const res=await fetch(source,{headers:{Accept:"image/*"}}).catch(()=>null);if(!res?.ok)return null;const contentType=res.headers.get("content-type")?.split(";")[0]?.trim();if(!contentType?.startsWith("image/"))return null;const bytes=new Uint8Array(await res.arrayBuffer());return bytes.length?{mimeType:contentType,data:bytesToBase64(bytes)}:null;}
function extractJson(text:string):Record<string,unknown>|null{const c=text.replace(/^```(?:json)?\s*/i,"").replace(/```\s*$/i,"").trim();try{const p=JSON.parse(c);return p&&typeof p==="object"?p:null;}catch{const m=c.match(/\{[\s\S]*\}/);if(!m)return null;try{return JSON.parse(m[0]);}catch{return null;}}}
function normalizeReview(raw:Record<string,unknown>|null,originalPrompt:string):StudioReview|null{if(!raw)return null;const scoreValue=typeof raw.score==="number"?raw.score:Number(raw.score);if(!Number.isFinite(scoreValue))return null;const score=Math.max(0,Math.min(10,scoreValue));const issues=Array.isArray(raw.issues)?raw.issues.filter((v):v is string=>typeof v==="string").slice(0,12):[];const improvedPrompt=clampPrompt(typeof raw.improvedPrompt==="string"&&raw.improvedPrompt.trim()?raw.improvedPrompt:originalPrompt);return{score,passed:raw.passed===true&&score===10&&issues.length===0,issues,improvedPrompt};}
export async function reviewVisual(kind:"image"|"model",originalPrompt:string,visualSource:string):Promise<StudioReview|null>{const inline=await imageToInlineData(visualSource);if(!inline)return null;const rubric=kind==="model"?"Perform an extremely strict production asset inspection: silhouette and proportions from every visible angle, completeness of every requested component, symmetry where appropriate, topology and geometry defects, holes, cracks, non-manifold-looking areas, floating or intersecting parts, duplicated or missing components, warped surfaces, bad joins, texture stretching, UV/material defects, blurry or missing textures, lighting/material inconsistencies, and exact fidelity to the request. Treat even a small visible defect as a failure.":"Perform an extremely strict production image inspection: composition, subject identity, anatomy/geometry, object boundaries, symmetry where appropriate, lighting, materials, perspective, fine details, text, artifacts, duplicated/missing objects, malformed areas, unwanted marks, and exact fidelity to the request. Treat even a small visible defect as a failure.";const instruction=`You are the final zero-tolerance production QA gate inside Zeros Studio. ${rubric}\n\nOriginal request: ${clampPrompt(originalPrompt)}\n\nInspect the supplied render itself. Return ONLY strict JSON: {"score": number from 0 to 10, "passed": boolean, "issues": [short strings], "improvedPrompt": "a rewritten generation prompt that fixes every detected issue while preserving the user's intent"}. A pass is allowed ONLY when genuinely production-ready, visually complete, faithful to the request, and you identify ZERO visible defects: score exactly 10, passed true, issues empty. If there is any visible uncertainty or defect, fail it and describe the repair. Be ruthless; do not praise or be generous.`;for(const model of visionModels)for(const key of geminiKeys())try{const res=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent`,{method:"POST",headers:{"x-goog-api-key":key,"Content-Type":"application/json"},body:JSON.stringify({contents:[{role:"user",parts:[{text:instruction},{inlineData:inline}]}],generationConfig:{temperature:.05,maxOutputTokens:2048,responseMimeType:"application/json"}})});if(!res.ok)continue;const json=(await res.json().catch(()=>null)) as {candidates?:{content?:{parts?:GeminiPart[]}}[]}|null;const text=(json?.candidates?.[0]?.content?.parts??[]).map(p=>p.text??"").join("").trim();const review=normalizeReview(extractJson(text),originalPrompt);if(review)return review;}catch{}return null;}
export function productionImagePrompt(prompt:string,issues:string[]=[]){return clampPrompt(`${prompt}. Create a finished, studio-grade image at the highest available image-model quality. Preserve every requested subject, style, medium, and composition detail; do not substitute a template or generic subject. Use deliberate art direction, physically coherent lighting and materials where applicable, sharp focal detail, natural texture variation, clean anatomy and geometry, coherent perspective, and complete edge-to-edge rendering. No malformed or duplicated elements, accidental text, watermark, blur, compression artifacts, or unfinished areas.${issues.length?` Fix every observed defect: ${issues.join("; ")}.`:""}`,1500);}
export function productionModelPrompt(prompt:string,issues:string[]=[]){return clampPrompt(`${prompt}. Create an elite AAA production asset from scratch: maximum geometric fidelity, accurate proportions, complete silhouette from every angle, coherent watertight-looking geometry, clean joins, no floating/intersecting/missing parts, intentional symmetry, crisp high-detail physically based materials, consistent UV-quality surfaces, physically plausible construction, game-production-ready presentation.${issues.length?` Correct every observed defect: ${issues.join("; ")}.`:""}`,1400);}
