// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';
import { firebaseAuth } from '@/lib/firebase';

function readEnv(keys: string[]): string {
  for (const key of keys) {
    // Vite inlines import.meta.env.VITE_* at build time for the browser bundle.
    const fromVite = (import.meta.env as Record<string, string | undefined>)[key];
    if (typeof fromVite === 'string' && fromVite.trim()) return fromVite.trim();
    // SSR / Cloudflare runtime
    const fromProcess = typeof process !== 'undefined' ? process.env?.[key] : undefined;
    if (typeof fromProcess === 'string' && fromProcess.trim()) return fromProcess.trim();
  }
  return '';
}

function createSupabaseClient() {
  // Cloudflare Pages must expose these as BUILD-time env vars (VITE_ prefix preferred).
  // Fall back to non-VITE names in case only SUPABASE_URL was configured.
  const SUPABASE_URL = readEnv([
    'VITE_SUPABASE_URL',
    'SUPABASE_URL',
    'NEXT_PUBLIC_SUPABASE_URL',
  ]);
  const SUPABASE_PUBLISHABLE_KEY = readEnv([
    'VITE_SUPABASE_PUBLISHABLE_KEY',
    'SUPABASE_PUBLISHABLE_KEY',
    'VITE_SUPABASE_ANON_KEY',
    'SUPABASE_ANON_KEY',
    'NEXT_PUBLIC_SUPABASE_ANON_KEY',
  ]);

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['VITE_SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['VITE_SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message =
      `Missing Supabase environment variable(s): ${missing.join(', ')}. ` +
      `In Cloudflare Pages → Settings → Environment variables, add them for Production, then trigger a new deploy.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  try {
    console.info(`[Supabase] client ready → ${new URL(SUPABASE_URL).host}`);
  } catch {
    console.error('[Supabase] SUPABASE_URL is not a valid URL:', SUPABASE_URL.slice(0, 40));
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    accessToken: async () => {
      try {
        const user = firebaseAuth.currentUser;
        if (!user) return null;
        return await user.getIdToken(false);
      } catch (e) {
        console.warn('[Supabase] getIdToken failed:', e);
        return null;
      }
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
