// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';
import { firebaseAuth } from '@/lib/firebase';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

/**
 * Custom fetch that:
 * 1. Always attaches the publishable apikey
 * 2. Avoids Request+init header bugs on WebKit by resolving to a URL string
 * 3. Keeps Firebase third-party JWT Authorization headers intact
 */
function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers();

    // Seed from Request headers first (if any), then overlay init headers.
    if (typeof Request !== 'undefined' && input instanceof Request) {
      input.headers.forEach((value, key) => headers.set(key, value));
    }
    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);

    // Resolve to a plain URL string so WebKit never sees conflicting Request+init shapes.
    const url =
      typeof input === 'string'
        ? input
        : input instanceof URL
          ? input.href
          : input.url;

    const method =
      init?.method ??
      (typeof Request !== 'undefined' && input instanceof Request ? input.method : undefined);

    const body =
      init?.body !== undefined
        ? init.body
        : typeof Request !== 'undefined' &&
            input instanceof Request &&
            method &&
            method !== 'GET' &&
            method !== 'HEAD'
          ? input.body
          : undefined;

    return fetch(url, {
      ...init,
      method,
      headers,
      body,
    });
  };
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env['VITE_SUPABASE_URL'] || process.env['SUPABASE_URL'];
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env['VITE_SUPABASE_PUBLISHABLE_KEY'] || process.env['SUPABASE_PUBLISHABLE_KEY'];

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    // Firebase is the source of truth for Google authentication.
    // Supabase's first-class Firebase third-party auth integration validates
    // the Firebase ID token on every Data API request.
    accessToken: async () => {
      try {
        const user = firebaseAuth.currentUser;
        if (!user) return null;
        // Prefer cached token; force-refresh only if the cached call fails.
        return await user.getIdToken(false);
      } catch (e) {
        console.warn('[Supabase] accessToken getIdToken failed:', e);
        try {
          return (await firebaseAuth.currentUser?.getIdToken(true)) ?? null;
        } catch {
          return null;
        }
      }
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: false,
      autoRefreshToken: false,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
